services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: "watchtower"
    command:
      - "--interval"
      - "30"
      - "rajsavac"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json

  traefik:
    image: 'traefik:v3.3'
    container_name: 'traefik'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=kristijan.rotim@icloud.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  svelteApp:
    build:
      context: .
      args:
        - DB_URL=http://pocketbase:8090
    image: ghcr.io/kristijan-rotim/rajsavac:latest
    container_name: 'rajsavac'
    # Remove or comment out the ports section since Traefik handles the routing
    # ports:
    #   - '5173:5173'
    environment:
      DB_URL: http://pocketbase:8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelteApp.rule=Host(`rajsavac.space`)"
      - "traefik.http.routers.svelteApp.entrypoints=websecure"
      - "traefik.http.routers.svelteApp.tls.certresolver=myresolver"
      - "traefik.http.services.svelteApp.loadbalancer.server.port=5173"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - '8090:8090'
    volumes:
      - ./pb_data:/pb_data
    command:
      - "--dir"
      - "/pb_data"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  letsencrypt:
  pocketbase_public:
